### PR TITLE
Add week-2 exercise solutions

### PR DESCRIPTION
**Pull request by claddyy**

### CODE REVIEW

**Review by rajarshimaitra — COMMENTED** [review]
Is the notebook complete? I can see many incomplete exercises..

**Comment by rajarshimaitra** [comment]
Also put your files inside the `solution` folder.

**Comment by claddyy** [comment]
> Is the notebook complete? I can see many incomplete exercises..

Yes, it was an error from my side, updated it.

**Review by rajarshimaitra — APPROVED** [review]
ACK 287ad411687395619a98d5359923820cef5ad74d

**Pull request merged**
