### PR TITLE
Week 3 homework

### PR DESCRIPTION
**Pull request by ch0k1**
Chapter 4: Serialization
Chapter 5: Transactions

### CODE REVIEW

**Comment by ch0k1** [comment]
@rajarshimaitra for some reason, I cannot put you as reviewer

**Comment by ch0k1** [comment]
Github_reviewer_label

**Comment by ch0k1** [comment]
I managed to find the following stack trace error:

`GraphQL error: Device does not have the correct permissions to execute 'RequestReviews'`

P.S. If you want me to be able to add you for a reviewer for the rest of the PRs, I would expect you to grand me  'RequestReviews' permissions mentioned above

**Review by rajarshimaitra — APPROVED** [review]
ACK e3730de53162abc045a0add890a48a2b1842c1c8

**Comment by rajarshimaitra** [comment]
> @rajarshimaitra for some reason, I cannot put you as reviewer

Totally fine, not needed. I have eye on this repo..

**Comment by ch0k1** [comment]
I just wanted to make your life easier with that proposal

**Pull request merged**
